---
default: true
whitespace: false
heading-increment: false
heading-style:
  style: atx
ul-style:
  style: dash
list-indent: true
ul-indent:
  indent: 4
no-trailing-spaces:
  br_spaces: 2
  list_item_empty_lines: true
no-hard-tabs: true
spaces_per_tab: 1
no-reversed-links: true
no-multiple-blanks: false
line-length: 1000
code_blocks: false
headers: true
heading_line_length: 200
stern: true
tables: false
commands-show-output: false
no-missing-space-atx: false
no-multiple-space-atx: true
no-missing-space-closed-atx: false
no-multiple-space-closed-atx: false
blanks-around-headings: false
heading-start-left: false
no-duplicate-heading:
  allow_different_nesting: true
single-h1: false
no-trailing-punctuation: true
no-multiple-space-blockquote: true
no-blanks-blockquote: false
ol-prefix:
  style: ordered
list-marker-space:
  ul_single: 3
  ol_single: 1
  ul_multi: 3
  ol_multi: 1
blanks-around-fences: true
list_items: false
blanks-around-lists: false
no-inline-html: false
no-bare-urls: true
hr-style:
  style: "* * *"
no-emphasis-as-heading: false
no-space-in-emphasis: true
no-space-in-code: true
no-space-in-links: true
fenced-code-language: true
first-line-h1: false
no-empty-links: true
required-headings: true
proper-names:
  names:
    - JavaScript
  html_elements: true
  code_blocks: true
no-alt-text: true
code-block-style:
  style: fenced
single-trailing-newline: true
code-fence-style:
  style: backtick
emphasis-style:
  style: asterisk
strong-style:
  style: asterisk
link-fragments: true
reference-links-images: true
link-image-reference-definitions: true
